title: Human-Centered Design DeCal
email: your-email@example.com
description: Description TBD
baseurl: ""
tagline: HCD DeCal

site-description: "Berkeley Innovation's Human-Centered Design DeCal is an introductory class to design theory and practice, with a focus on human-centered design."
extended-description: In this course facilitated by Berkeley Innovation, students learn about the human-centered design process and theory, and engage in hands-on activities during class and in homework assignments. Throughout the semester, students will use industry standard tools to solve a problem they care about in their midterm and final project.

about-bi: We are UC Berkeley’s first student-run design organization since 2003.
about-bi-long: We are UC Berkeley’s first student-run design organization since 2003. As a human-centered design consultancy, we work with clients on projects ranging from physical to digital products, brands, and experiences.
bi-url: https://berkeleyinnovation.org

app-url: https://forms.gle/McG7HF5P2f8BVBfj9
app-deadline: January 24, 2023

plugins:
  - jekyll-notion
  - jekyll-toc

permalink: pretty

sass:
  sass_dir: _scss

kramdown:
  parse_block_html: true

toc:
  min_level: 2
  max_level: 3
    
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  -
    scope:
      path: ""
      type: assignments
    values:
      layout: docs
      toc: true

collections:
  assignments:
    output: true

notion:
  databases:
    - id: 1b9c885292434a93839a8e590c51ba5d
      collection: assignments
    - id: 7bb8b112533649039a6ce4588a83cfa2
      data: schedule
      sorts: [{ "property": "Meeting Date", "direction": "ascending" }]
    - id: 5cf9ab87b30e4851b92e422673fa6bd2
      data: staff
      sorts: [{ "property": "Role", "direction": "descending" }]
    - id: ed8263c9b84a41b489e8023febf85dd1
      data: faqs
    - id: 80d0187af1a74f27b13aec16e7674f23
      data: announcement
      sorts: [{ "property": "Date", "direction": "descending" }]
  pages:
    - id: 4469aa32c57247cd94e8994f04ef694f # Syllabus

gems:
  - jekyll-liquify
