title: Human-Centered Design DeCal
email: your-email@example.com
description: Description TBD
baseurl: ""
tagline: HCD DeCal

about-bi: We are UC Berkeley’s first student-run design organization since 2003.
bi-url: https://berkeleyinnovation.org

plugins:
  - jekyll-feed
  - jekyll-toc

sass:
  sass_dir: assets/css

kramdown:
  parse_block_html: true

toc:
  min_level: 2
  max_level: 3
