title: Human-Centered Design DeCal
email: your-email@example.com
description: Description TBD
baseurl: ""
tagline: HCD DeCal

site-description: "Berkeley Innovation's Human-Centered Design DeCal is an introductory class to design theory and practice, with a focus on human-centered design."

about-bi: We are UC Berkeley’s first student-run design organization since 2003.
about-bi-long: We are UC Berkeley’s first student-run design organization since 2003. As a human-centered design consultancy, we work with clients on projects ranging from physical to digital products, brands, and experiences.
bi-url: https://berkeleyinnovation.org
app-url: /construction
app-deadline: January 12, 2023

plugins:
  - jekyll-toc

sass:
  sass_dir: _scss

kramdown:
  parse_block_html: true

toc:
  min_level: 2
  max_level: 3
