# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: the human-centered design decal
tagline: hcd decal
email: staff@hcd-decal.org
description: >- # this means to ignore newlines until "baseurl:"
  The course website for Berkeley Innovation's Human-Centered Design DeCal—a student taught course at UC Berkeley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hcd-decal.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
sass:
  sass_dir: _scss

plugins:
  - jekyll-notion
  - jekyll-toc

permalink: pretty

toc:
  min_level: 2
  max_level: 3
    
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  -
    scope:
      path: ""
      type: assignments
    values:
      layout: docs
      toc: true
  -
    scope:
      path: ""
      type: individual-pages
    values:
      toc: true
  -
    scope:
      path: ""
      type: redirect
    values:
      layout: "redirect"

collections:
  assignments:
    output: true
  individual-pages:
    output: true
  redirect:
    output: true

notion:
  databases:
    - id: db789909f475462c9c9c8ec4f3449d49
      collection: individual-pages
    - id: 6f706551c9db4858bf46e794adeb1a37
      collection: assignments
    - id: fec35ea7866042bab55fa15426a28631
      data: schedule
      sorts: [{ "property": "Meeting Date", "direction": "ascending" }]
    - id: ab83dddc32324397b051ad48cd343d84
      data: staff
      sorts: [{ "property": "Role", "direction": "descending" }]
    - id: 24c3579cae474a1da23147530e2a21a5
      data: faqs
    - id: 652389ecf59e43979c4ee950c4420f46
      collection: redirect
    

app-url: "https://docs.google.com/forms/d/e/1FAIpQLSecMsEe9FXMsgRQqCbyXNCMF5ds-dY57TAK38_315NLfXuZWw/viewform"
gems:
  - jekyll-liquify
